

services:
  postgres:
    image: postgres:17
    container_name: todolist-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: todolistdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
